fix: cli error messages printed correctly
Previously, error messages were printed as:
```
ERROR: <file><message>
```
instead of
```
ERROR: <file>
<message>
```